### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/pug#11]
Run the tests to see what the exact error is and track down the bug. Follow the guide and if you have any questions,  be sure to ask!

**Comment by Thomas-Elder** [comment]
I would like to try this one. 

Quick question though. I got a syntax error when running the tests the first time, which I've corrected and the tests now run. 

There are two other failing tests, which are unrelated. Are you aware of these too? Would you like separate issues created for those failing tests? 

Cheers,
Tom

**Comment by dfrownfelter** [comment]
What were the errors? The syntax error was the only intended error so you should be fine

**Comment by Thomas-Elder** [comment]
The two tests that are still failing are:
* test cases - filters include custom
* test cases - includes

Are these not failing for you too? 

I just created a pull request for the syntax error correction, so hopefully that's all good.

**Comment by dfrownfelter** [comment]
No they're not failing for me. I looked into it, and couldn't see why yours would fail. Errors can sometimes happen on different systems. You solved the main error though, good job!

**Comment by Thomas-Elder** [comment]
Ok sure, thanks for checking it out. 

And thanks! First pull request. Pumped for more. I'll probably look at contributing at some point too as I get a better handle on things. Thanks for setting this up, I think it's a great way to get started getting involved.

**Comment by dfrownfelter** [comment]
Awesome! I'm glad I could help. Now you can go work on any project you want. If you do ever want to contribute let me know, you would basically have a project of your own that you would create bugs for and manage the pull requests.
