### ISSUE TITLE
There's an Error!

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/pug#21]
There's an error in the code when running the test suite. Find out what's causing the error and solve it. To work on this bug, comment on this issue, and follow the guide in the readme.

**Comment by TawabG** [comment]
I'd like to solve this one.

**Comment by TawabG** [comment]
I encountered another error while testing:

https://gyazo.com/3dbc393856fd49fad59a364159e5d6e1

Even though I fixed the ''main'' problem, this one kept re-occuring:S
